# Generated by Django 4.0.3 on 2022-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI', '0002_rename_articulos_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
