# Generated by Django 4.0.3 on 2022-05-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI', '0006_alter_articulo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='Updated',
        ),
    ]
