# Generated by Django 4.0.3 on 2022-05-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI', '0007_remove_articulo_created_remove_articulo_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
